<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iDM_DSL" nsURI="http://www.example.org/iDM_DSL" nsPrefix="iDM_DSL">
  <eClassifiers xsi:type="ecore:EClass" name="Movement" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="speed" eType="#//Speed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="Front" literal="Front"/>
    <eLiterals name="Back" value="1" literal="Back"/>
    <eLiterals name="Right" value="2" literal="Right"/>
    <eLiterals name="Left" value="3" literal="Left"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AngleUnit">
    <eLiterals name="Degre" literal="Degre"/>
    <eLiterals name="Radian" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returntype" eType="#//ReturnType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angleUnit" eType="#//AngleUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angleValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensors">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SensorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//DistanceUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Units">
    <eLiterals name="MM_S" literal="MM_S"/>
    <eLiterals name="CM_S" value="1" literal="CM_S"/>
    <eLiterals name="M_S" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStruct" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpr" eSuperTypes="#//NumberExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//NumberExpr"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//NumberExpr"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BooleanOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//ControlStruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//ControlStruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanexpr" eType="#//BooleanExpr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="ADD"/>
    <eLiterals name="SUB" value="1"/>
    <eLiterals name="MUL" value="2"/>
    <eLiterals name="DIV" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperator">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="NOT" value="2"/>
    <eLiterals name="EQUALS" value="3"/>
    <eLiterals name="LESS" value="4"/>
    <eLiterals name="GREATER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="TIME"/>
    <eLiterals name="DISTANCE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DistanceUnit">
    <eLiterals name="CM"/>
    <eLiterals name="M" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Units"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntExpression" eSuperTypes="#//NumberExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberExpr" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignement" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//Instruction"/>
  </eClassifiers>
</ecore:EPackage>
